Reject Approvals Older Than One Year
ServiceNowDevProgram/code-snippets pull request #1609
Opened 2024-10-31 17:27 UTC by pallipoina92

The overall purpose of this script is to identify and reject approval requests that are older than one year and are still in the "requested" state. This helps in cleaning up old approvals that may no longer be relevant.

2024-10-31 21:48 UTC, Lacah requested changes

2024-10-31 21:48 UTC, Lacah commented on Scheduled Jobs/Reject approvals created before an year/readme.md
This is not a real readme, only the same code with some comments (which you could just add to the actual js file).
Could you add some actual description here about the purpose of the script and what should someone who wants to use it do?
Thanks.

2024-11-01 00:17 UTC, pallipoina92 commented
Hi,

Sure, will do that.

Thanks,
Sunil

On Fri, 1 Nov 2024 at 3:19 AM, Laszlo ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> On Scheduled Jobs/Reject approvals created before an year/readme.md
> <https://github.com/ServiceNowDevProgram/code-snippets/pull/1609#discussion_r1825205047>
> :
>
> This is not a real readme, only the same code with some comments (which
> you could just add to the actual js file).
> Could you add some actual description here about the purpose of the script
> and what should someone who wants to use it do?
> Thanks.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ServiceNowDevProgram/code-snippets/pull/1609#pullrequestreview-2409170816>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH6EI3CE26CA6QTSWZ2ORKDZ6KQWBAVCNFSM6AAAAABQ6YZWYGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIMBZGE3TAOBRGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2024-11-01 00:45 UTC, pallipoina92 commented on Scheduled Jobs/Reject approvals created before an year/readme.md
Hi, I have updated the readme.md file and committed the changes, is there anything else that I need to do?

2024-11-01 06:59 UTC, Lacah commented on Scheduled Jobs/Reject approvals created before an year/readme.md
This is sufficient, thanks.

2024-11-01 06:59 UTC, Lacah approved these changes

2024-11-01 06:59 UTC, merged