RITM rejection notes
ServiceNowDevProgram/code-snippets pull request #706
Opened 2023-10-02 18:53 UTC by brenduh

After finding that reject reasons added from Employee Center for Requests do not get added to the Approval record but instead the RITM record, I made a change to the reject_reason email script to include the RITM reject reason (if found). The notification email script calls the RequestNotificationUtil script include to pull the reject reason journal entry (if found) to be used for Notifications.

2023-10-02 19:18 UTC, MGOPW requested changes
Please add the `.js` extension to the end of the file name for proper formatting.

2023-10-02 19:20 UTC, MGOPW approved these changes

2023-10-02 19:20 UTC, brenduh reviewed
Added .js to file names

2023-10-03 04:19 UTC, earlduque commented
Thank you for your contribution. However, it doesn’t comply with our contributing guidelines. As a reminder, the general requirements (as outlined in the [CONTRIBUTING.md file](https://github.com/ServiceNowDevProgram/code-snippets/blob/main/CONTRIBUTING.md)) are the following: follow the folder+subfolder guidelines and include a readme.md file explaining what the code snippet does. Review your contribution against the guidelines and make the necessary adjustments. Closing this for now. Once you make additional changes, feel free to re-open this Pull Request or create a new one.

> Script Includes/RequestNotificationUtil.js

2023-10-03 04:19 UTC, closed without merging